
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      

microservice:
  payment-service:
    endpoints:
      getPaymentById:
        uri : http://PAYMENT-SERVICE/payments/
  user-service:
    endpoints:
      getUserById:
        uri : http://USER-SERVICE/users/ 
